-- Керівні документи для Посібника
CREATE TABLE IF NOT EXISTS guide_documents (
  id bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  title text NOT NULL,           -- Назва документа (наприклад, "ПВП ДАУ")
  title_short text NOT NULL,      -- Коротка назва для кнопок (наприклад, "ПВП ДАУ")
  order_num integer NOT NULL DEFAULT 0,  -- Порядок сортування
  created_at timestamptz DEFAULT now()
);

-- Розділи документів
CREATE TABLE IF NOT EXISTS guide_sections (
  id bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  document_id bigint NOT NULL REFERENCES guide_documents(id) ON DELETE CASCADE,
  parent_id bigint REFERENCES guide_sections(id) ON DELETE CASCADE,  -- Для підрозділів
  title text NOT NULL,           -- Назва розділу
  content text,                  -- Вміст розділу (може бути null для папок)
  order_num integer NOT NULL DEFAULT 0,
  created_at timestamptz DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_guide_sections_document ON guide_sections(document_id);
CREATE INDEX IF NOT EXISTS idx_guide_sections_parent ON guide_sections(parent_id);
